### PR TITLE
easy installer

### PR DESCRIPTION
**Pull request by MISTERNEGATIVE21**
plz check this installer

### CODE REVIEW

**Review by MISTERNEGATIVE21 — COMMENTED** [review]
looks ok

**Review by MISTERNEGATIVE21 — COMMENTED** [review]
final check

**Review by anuran-roy — CHANGES_REQUESTED** [review]
## Issues to take care of:

1.  Send the pull request to the `dev` branch and NOT the `main` branch.

2. Can you just change `python-dev` to `python3-dev` in lines 65 to 67? I think that Python 2.7 is being installed and Python3 is being removed from the default `python` alias for some distros.

Great work on the other parts! 😄 

## Example screenshot:
image

**Comment by MISTERNEGATIVE21** [comment]
Ok understood

**Pull request closed without merging**
